name: Sync GitHub to GitLab

on:
  push:
    branches:
      - master  # Adjust branch if needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:$GITLAB_TOKEN@git.gvk.idi.ntnu.no/amundfpl/Country-Information-Service.git
          git fetch --unshallow  # Ensures history is available
          git push --force --mirror gitlab
