name: Sync GitHub to GitLab

on:
  push:
    branches:
      - dev  # Adjust branch if needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:$GITLAB_TOKEN@https://git.gvk.idi.ntnu.no/course/prog2005/prog2005-2025-workspace/amundfpl/assignment-1
          git fetch --unshallow  # Ensures full commit history
          git push gitlab dev:dev  # Push GitHub 'dev' branch to GitLab 'dev' branch